name: hope_doctor
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/launcher_icon.png"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  #Flutter Dependencies here
  hexcolor: ^1.0.2
  flutter_dotenv: ^2.1.0
  flutter_svg: ^0.18.0
  flushbar: ^1.10.4
  google_maps_flutter: ^1.0.2
  geolocator: ^6.1.8+1
  mdi: ^3.0.0
  http: ^0.12.1
  geoflutterfire: ^2.2.1
  firebase_core: ^0.5.0
  flutter_rating_bar: ^3.0.1+1
  cached_network_image: ^2.2.0+1
  provider: ^3.2.0
  bubble: ^1.1.9+1
  emojis: ^0.9.3
  circular_profile_avatar: ^1.0.6
  video_player: ^1.0.1
  shimmer: ^1.1.2
  fluttertoast: ^7.0.1+1
  url_launcher: ^5.7.0
  email_validator: '^1.0.0'
  flutter_fadein: ^1.1.1
  flutter_spinkit: "^4.1.2"
  carousel_slider: ^3.0.0
  simple_animations: ^1.3.4
  page_transition: ^1.1.5
  lottie: ^0.4.1
  pinput: ^0.2.0
  flutter_datetime_picker: ^1.4.0
  shared_preferences: ^0.5.12+4
  smooth_page_indicator: ^0.2.0
  firebase_messaging: ^7.0.3
  device_info: ^1.0.0
  localstorage: ^3.0.0
  connectivity: ^0.4.9
  cloud_firestore: ^0.14.4
  flutter_calendar_carousel: ^1.5.3

flutter:

  uses-material-design: true
  #assets here
  assets:
    - images/
    - images/icons/
    - fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/lato/LatoBlack.ttf
          weight: 700
        - asset: fonts/lato/LatoBold.ttf
          weight: 300
        - asset: fonts/lato/LatoRegular.ttf
          weight: 200

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true