name: hope_doctor
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/launcher_icon.png"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #Flutter Dependencies here
  hexcolor: ^2.0.3
  flutter_dotenv: ^3.1.0
  flutter_svg: ^0.22.0
  flushbar: ^1.10.4
  google_maps_flutter: ^2.0.3
  geolocator: ^7.0.3
  mdi: ^4.0.0
  http: ^0.13.2
  timeago: ^3.0.2
  flutter_rating_bar: ^4.0.0
  provider: ^5.0.0
  bubble: ^1.2.1
  emojis: ^0.9.3
  circular_profile_avatar: ^2.0.0
  video_player: ^2.1.1
  shimmer: ^2.0.0
  fluttertoast: ^8.0.6
  email_validator: '^1.0.0'
  flutter_fadein: ^2.0.0
  flutter_spinkit: "^4.1.2"
  carousel_slider: ^3.0.0
  simple_animations: ^3.1.1
  page_transition: ^1.1.7+6
  lottie: ^1.0.1
  pinput: ^1.2.0
  flutter_datetime_picker: ^1.5.1
  shared_preferences: ^2.0.5
  smooth_page_indicator: ^0.2.3
  localstorage: ^4.0.0+1
  flutter_calendar_carousel: ^2.0.1

flutter:

  uses-material-design: true
  #assets here
  assets:
    - images/
    - images/icons/
    - fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/lato/LatoBlack.ttf
          weight: 700
        - asset: fonts/lato/LatoBold.ttf
          weight: 300
        - asset: fonts/lato/LatoRegular.ttf
          weight: 200

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true